### ISSUE TITLE
Add `assert.expect` to generated tests

### ISSUE THREAD

**Issue by trentmwillis** [rwjblue/broccoli-jshint#36]
We'd like to turn on [`QUnit.config.requireExpects`](https://api.qunitjs.com/QUnit.config/) in our project and in order to do so we need our JSHint tests to also add an `assert.expect` statement.

I realize it doesn't add a whole lot of value to the generated tests, but it would be nice to offer developers the option to use `requireExpects` with this module.

If this sounds reasonable I'll make the required PR (should be simple).

**Comment by rwjblue** [comment]
Ya, I'm game!
